# Generated by Django 2.2.4 on 2019-08-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='../static/img/square-ppic.jpg', upload_to='project_image'),
        ),
    ]
