# Generated by Django 2.2.4 on 2019-08-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190823_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
