# Generated by Django 2.2.4 on 2019-08-23 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=462)),
                ('image', models.ImageField(default='../static/available_hostels/img/001.jpg', upload_to='hostel_image')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(default='', max_length=250, unique_for_date='publish')),
                ('facilities', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
